//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioss.Ultrasound.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bioss.Ultrasound.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FMP.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        internal static string BiometricPopup_Comment {
            get {
                return ResourceManager.GetString("BiometricPopup_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diastolic.
        /// </summary>
        internal static string BiometricPopup_Diastolic {
            get {
                return ResourceManager.GetString("BiometricPopup_Diastolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data entered incorrectly.
        /// </summary>
        internal static string BiometricPopup_ErrorEnter {
            get {
                return ResourceManager.GetString("BiometricPopup_ErrorEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pulse.
        /// </summary>
        internal static string BiometricPopup_Pulse {
            get {
                return ResourceManager.GetString("BiometricPopup_Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sugar.
        /// </summary>
        internal static string BiometricPopup_Sugar {
            get {
                return ResourceManager.GetString("BiometricPopup_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Systolic.
        /// </summary>
        internal static string BiometricPopup_Systolic {
            get {
                return ResourceManager.GetString("BiometricPopup_Systolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        internal static string BiometricPopup_Temperature {
            get {
                return ResourceManager.GetString("BiometricPopup_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Biometric.
        /// </summary>
        internal static string BiometricPopup_Title {
            get {
                return ResourceManager.GetString("BiometricPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth search....
        /// </summary>
        internal static string BluetoothSearch {
            get {
                return ResourceManager.GetString("BluetoothSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FHR, bpm.
        /// </summary>
        internal static string Chart_FHRAxysTitle {
            get {
                return ResourceManager.GetString("Chart_FHRAxysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOCO, %.
        /// </summary>
        internal static string Chart_TOCOAxysTitle {
            get {
                return ResourceManager.GetString("Chart_TOCOAxysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Dawes-Redman criteria have been met.
        /// </summary>
        internal static string DawesRedmanCriteriaMetMessage {
            get {
                return ResourceManager.GetString("DawesRedmanCriteriaMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Dawes-Redman criteria are not met.
        /// </summary>
        internal static string DawesRedmanCriteriaNotMetMessage {
            get {
                return ResourceManager.GetString("DawesRedmanCriteriaNotMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect from device?.
        /// </summary>
        internal static string Dialog_DisconnectMessage {
            get {
                return ResourceManager.GetString("Dialog_DisconnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The recording time has expired. To complete?.
        /// </summary>
        internal static string Dialog_RecordCompleted {
            get {
                return ResourceManager.GetString("Dialog_RecordCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на privacy.txt.
        /// </summary>
        internal static string DocPrivacy {
            get {
                return ResourceManager.GetString("DocPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loss percentage.
        /// </summary>
        internal static string LossPercentage {
            get {
                return ResourceManager.GetString("LossPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loss/min: {0} %.
        /// </summary>
        internal static string LossPercentageMin {
            get {
                return ResourceManager.GetString("LossPercentageMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To stop recording, hold down the Stop button for 2 seconds.
        /// </summary>
        internal static string Main_HoldStopButton {
            get {
                return ResourceManager.GetString("Main_HoldStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        internal static string Menu_AboutDescription {
            get {
                return ResourceManager.GetString("Menu_AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change app settings.
        /// </summary>
        internal static string Menu_SettingsDescription {
            get {
                return ResourceManager.GetString("Menu_SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 27/3*.
        /// </summary>
        internal static string PDF_27_3 {
            get {
                return ResourceManager.GetString("PDF_27_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Acc. &gt; 10 bpm.
        /// </summary>
        internal static string PDF_AccCountMore10 {
            get {
                return ResourceManager.GetString("PDF_AccCountMore10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Acc. &gt; 15 bpm.
        /// </summary>
        internal static string PDF_AccCountMore15 {
            get {
                return ResourceManager.GetString("PDF_AccCountMore15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basal FHR, bpm (110-160).
        /// </summary>
        internal static string PDF_BasalFHRRange110_160 {
            get {
                return ResourceManager.GetString("PDF_BasalFHRRange110_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patient comment.
        /// </summary>
        internal static string PDF_Comment {
            get {
                return ResourceManager.GetString("PDF_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Dawson-Redman criteria are met..
        /// </summary>
        internal static string PDF_DawsonRedmanCriteriaMet {
            get {
                return ResourceManager.GetString("PDF_DawsonRedmanCriteriaMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Dawson-Redman criteria are not met.
        /// </summary>
        internal static string PDF_DawsonRedmanCriteriaNoMet {
            get {
                return ResourceManager.GetString("PDF_DawsonRedmanCriteriaNoMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of Dec. &gt; 20 bpm.
        /// </summary>
        internal static string PDF_DecCountMore20 {
            get {
                return ResourceManager.GetString("PDF_DecCountMore20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doctor&apos;s conclusion:.
        /// </summary>
        internal static string PDF_DoctorsConclusion {
            get {
                return ResourceManager.GetString("PDF_DoctorsConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        internal static string PDF_EmptyValue {
            get {
                return ResourceManager.GetString("PDF_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---(---).
        /// </summary>
        internal static string PDF_EmptyValueLTV {
            get {
                return ResourceManager.GetString("PDF_EmptyValueLTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - STVlasting ≥ 5 minutes and one acceleration &gt;15 beats/min..
        /// </summary>
        internal static string PDF_EpisodeCondition28Plus {
            get {
                return ResourceManager.GetString("PDF_EpisodeCondition28Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - or STV lasting ≥ 7 minutes;
        ///- or STV lasting ≥ 5 minutes and one acceleration &gt;10 beats/min..
        /// </summary>
        internal static string PDF_EpisodeConditionSTV {
            get {
                return ResourceManager.GetString("PDF_EpisodeConditionSTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fetal movements.
        /// </summary>
        internal static string PDF_FetalMovements {
            get {
                return ResourceManager.GetString("PDF_FetalMovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на page {0} of {1}.
        /// </summary>
        internal static string PDF_FooterPageNumbers {
            get {
                return ResourceManager.GetString("PDF_FooterPageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor Name: {0}.
        /// </summary>
        internal static string PDF_FooterSN {
            get {
                return ResourceManager.GetString("PDF_FooterSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gestational age.
        /// </summary>
        internal static string PDF_GestationalAge {
            get {
                return ResourceManager.GetString("PDF_GestationalAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default gestation period.
        /// </summary>
        internal static string PDF_GestationalAgeByDefault {
            get {
                return ResourceManager.GetString("PDF_GestationalAgeByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string PDF_HeaderDateOfResearch {
            get {
                return ResourceManager.GetString("PDF_HeaderDateOfResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doctor.
        /// </summary>
        internal static string PDF_HeaderDoctor {
            get {
                return ResourceManager.GetString("PDF_HeaderDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FMP &quot;BIPULS&quot;.
        /// </summary>
        internal static string PDF_HeaderLeftCorner {
            get {
                return ResourceManager.GetString("PDF_HeaderLeftCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patient.
        /// </summary>
        internal static string PDF_HeaderPatient {
            get {
                return ResourceManager.GetString("PDF_HeaderPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heart rate.
        /// </summary>
        internal static string PDF_HeartRate {
            get {
                return ResourceManager.GetString("PDF_HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High variability, min.
        /// </summary>
        internal static string PDF_HighVariability {
            get {
                return ResourceManager.GetString("PDF_HighVariability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low variability, min.
        /// </summary>
        internal static string PDF_LowVariability {
            get {
                return ResourceManager.GetString("PDF_LowVariability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LTV, ms (bpm).
        /// </summary>
        internal static string PDF_LTV {
            get {
                return ResourceManager.GetString("PDF_LTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mother parameters.
        /// </summary>
        internal static string PDF_MotherParameters {
            get {
                return ResourceManager.GetString("PDF_MotherParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not specified.
        /// </summary>
        internal static string PDF_NotSpecified {
            get {
                return ResourceManager.GetString("PDF_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Oscillation frequency, ms.
        /// </summary>
        internal static string PDF_OscillationFrequency {
            get {
                return ResourceManager.GetString("PDF_OscillationFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pulse.
        /// </summary>
        internal static string PDF_Pulse {
            get {
                return ResourceManager.GetString("PDF_Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pulse, bpm.
        /// </summary>
        internal static string PDF_PulseBpm {
            get {
                return ResourceManager.GetString("PDF_PulseBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording duration.
        /// </summary>
        internal static string PDF_RecordingDuration {
            get {
                return ResourceManager.GetString("PDF_RecordingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording duration, min(≥10).
        /// </summary>
        internal static string PDF_RecordingDurationMin10 {
            get {
                return ResourceManager.GetString("PDF_RecordingDurationMin10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signal loss, % (≤ 20).
        /// </summary>
        internal static string PDF_SignalLossMax20 {
            get {
                return ResourceManager.GetString("PDF_SignalLossMax20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Signal loss.
        /// </summary>
        internal static string PDF_SignaLoss {
            get {
                return ResourceManager.GetString("PDF_SignaLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sin. rhythm, min(≤2).
        /// </summary>
        internal static string PDF_SinusRhythmMin2 {
            get {
                return ResourceManager.GetString("PDF_SinusRhythmMin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STV, ms (≥ 4).
        /// </summary>
        internal static string PDF_STVMin4 {
            get {
                return ResourceManager.GetString("PDF_STVMin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sugar.
        /// </summary>
        internal static string PDF_Sugar {
            get {
                return ResourceManager.GetString("PDF_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sugar, mmol/L.
        /// </summary>
        internal static string PDF_SugarMmolL {
            get {
                return ResourceManager.GetString("PDF_SugarMmolL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTG parameters.
        /// </summary>
        internal static string PDF_TableCTGParameters {
            get {
                return ResourceManager.GetString("PDF_TableCTGParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mother parameters.
        /// </summary>
        internal static string PDF_TableMotherParameters {
            get {
                return ResourceManager.GetString("PDF_TableMotherParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature.
        /// </summary>
        internal static string PDF_Temperature {
            get {
                return ResourceManager.GetString("PDF_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temperature, °C.
        /// </summary>
        internal static string PDF_TemperatureC {
            get {
                return ResourceManager.GetString("PDF_TemperatureC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time-dependent parameters.
        /// </summary>
        internal static string PDF_TimeDependentParameters {
            get {
                return ResourceManager.GetString("PDF_TimeDependentParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequency of UC, 1/h (≥ 3).
        /// </summary>
        internal static string PDF_UCFrequencyMin3 {
            get {
                return ResourceManager.GetString("PDF_UCFrequencyMin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} years.
        /// </summary>
        internal static string PDF_UserBirthdayDescriptionAge {
            get {
                return ResourceManager.GetString("PDF_UserBirthdayDescriptionAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To use this application the {0} permission is required. Please go into Settings and turn on {0} for the app..
        /// </summary>
        internal static string PermissionDialogQuestion2 {
            get {
                return ResourceManager.GetString("PermissionDialogQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} Permission.
        /// </summary>
        internal static string PermissionDialogTitle {
            get {
                return ResourceManager.GetString("PermissionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete this record?.
        /// </summary>
        internal static string Record_DialogDeleteMessage {
            get {
                return ResourceManager.GetString("Record_DialogDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting.
        /// </summary>
        internal static string Record_DialogDeleteTitle {
            get {
                return ResourceManager.GetString("Record_DialogDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You don&apos;t have any records.
        /// </summary>
        internal static string Records_EmptyList {
            get {
                return ResourceManager.GetString("Records_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Records.
        /// </summary>
        internal static string Records_Title {
            get {
                return ResourceManager.GetString("Records_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto connect.
        /// </summary>
        internal static string Settings_AutoConnect {
            get {
                return ResourceManager.GetString("Settings_AutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The app will automatically connect to the first device it detects.
        /// </summary>
        internal static string Settings_AutoConnectDescription {
            get {
                return ResourceManager.GetString("Settings_AutoConnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto end recording.
        /// </summary>
        internal static string Settings_AutoMonitor {
            get {
                return ResourceManager.GetString("Settings_AutoMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatic reset TOCO.
        /// </summary>
        internal static string Settings_AutoToco {
            get {
                return ResourceManager.GetString("Settings_AutoToco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FHR area.
        /// </summary>
        internal static string Settings_ChartFHRArea {
            get {
                return ResourceManager.GetString("Settings_ChartFHRArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale.
        /// </summary>
        internal static string Settings_ChartScale {
            get {
                return ResourceManager.GetString("Settings_ChartScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select scale.
        /// </summary>
        internal static string Settings_ChartScalePageTitle {
            get {
                return ResourceManager.GetString("Settings_ChartScalePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} min.
        /// </summary>
        internal static string Settings_ChartVariantsMinuteFormat {
            get {
                return ResourceManager.GetString("Settings_ChartVariantsMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}-{1} bpm.
        /// </summary>
        internal static string Settings_ChartYScaleFormat {
            get {
                return ResourceManager.GetString("Settings_ChartYScaleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection.
        /// </summary>
        internal static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doctor.
        /// </summary>
        internal static string Settings_Doctor {
            get {
                return ResourceManager.GetString("Settings_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter name.
        /// </summary>
        internal static string Settings_DoctorPlaceholder {
            get {
                return ResourceManager.GetString("Settings_DoctorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personal device.
        /// </summary>
        internal static string Settings_IsPersonal {
            get {
                return ResourceManager.GetString("Settings_IsPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select if using the device personally.
        /// </summary>
        internal static string Settings_IsPersonalDescription {
            get {
                return ResourceManager.GetString("Settings_IsPersonalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor.
        /// </summary>
        internal static string Settings_Monitor {
            get {
                return ResourceManager.GetString("Settings_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm completion of recording.
        /// </summary>
        internal static string Settings_MonitorConfirmRecordCompletion {
            get {
                return ResourceManager.GetString("Settings_MonitorConfirmRecordCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A dialog will be displayed to confirm the completion of the recording after the specified time has elapsed.
        /// </summary>
        internal static string Settings_MonitorConfirmRecordCompletionDescription {
            get {
                return ResourceManager.GetString("Settings_MonitorConfirmRecordCompletionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} min.
        /// </summary>
        internal static string Settings_MonitorFinishMinuteFormat {
            get {
                return ResourceManager.GetString("Settings_MonitorFinishMinuteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording time.
        /// </summary>
        internal static string Settings_MonitorFinishTimes {
            get {
                return ResourceManager.GetString("Settings_MonitorFinishTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound signal when the battery is low.
        /// </summary>
        internal static string Settings_MonitorSoundBatteryLow {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundBatteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notification volume.
        /// </summary>
        internal static string Settings_MonitorSoundLevel {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound signal for large signal loss.
        /// </summary>
        internal static string Settings_MonitorSoundLossData {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundLossData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Organization.
        /// </summary>
        internal static string Settings_Organization {
            get {
                return ResourceManager.GetString("Settings_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter organization.
        /// </summary>
        internal static string Settings_OrganizationPlaceholder {
            get {
                return ResourceManager.GetString("Settings_OrganizationPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recording speed.
        /// </summary>
        internal static string Settings_PdfRecordingSpeed {
            get {
                return ResourceManager.GetString("Settings_PdfRecordingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} cm/min.
        /// </summary>
        internal static string Settings_PdfRecordingSpeedFormat {
            get {
                return ResourceManager.GetString("Settings_PdfRecordingSpeedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pregnancy number.
        /// </summary>
        internal static string Settings_PregnancyNumber {
            get {
                return ResourceManager.GetString("Settings_PregnancyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gestation period.
        /// </summary>
        internal static string Settings_PregnancyStart {
            get {
                return ResourceManager.GetString("Settings_PregnancyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gestation period not entered.
        /// </summary>
        internal static string Settings_PregnancyStartDescriptionNotSelected {
            get {
                return ResourceManager.GetString("Settings_PregnancyStartDescriptionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are pregnant {0} weeks and {1} days.
        /// </summary>
        internal static string Settings_PregnancyStartDescriptionTime {
            get {
                return ResourceManager.GetString("Settings_PregnancyStartDescriptionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chart.
        /// </summary>
        internal static string Settings_SectionChart {
            get {
                return ResourceManager.GetString("Settings_SectionChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        internal static string Settings_SectionInfo {
            get {
                return ResourceManager.GetString("Settings_SectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PDF.
        /// </summary>
        internal static string Settings_SectionPdf {
            get {
                return ResourceManager.GetString("Settings_SectionPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth.
        /// </summary>
        internal static string Settings_UserBirthday {
            get {
                return ResourceManager.GetString("Settings_UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are {0} full years old.
        /// </summary>
        internal static string Settings_UserBirthdayDescriptionAge {
            get {
                return ResourceManager.GetString("Settings_UserBirthdayDescriptionAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth not entered.
        /// </summary>
        internal static string Settings_UserBirthdayDescriptionNotSelected {
            get {
                return ResourceManager.GetString("Settings_UserBirthdayDescriptionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Settings_UserName {
            get {
                return ResourceManager.GetString("Settings_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your name.
        /// </summary>
        internal static string Settings_UserNamePlaceholder {
            get {
                return ResourceManager.GetString("Settings_UserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application is designed to work with the Fetal Monitor. It requires bluetooth permission to work..
        /// </summary>
        internal static string Startup_PermissionsMessage {
            get {
                return ResourceManager.GetString("Startup_PermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Permission.
        /// </summary>
        internal static string Startup_RequestPermissions {
            get {
                return ResourceManager.GetString("Startup_RequestPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn on your device.
        /// </summary>
        internal static string TurnOnYourDevice {
            get {
                return ResourceManager.GetString("TurnOnYourDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mmol/l.
        /// </summary>
        internal static string Unit_BloodGlucose {
            get {
                return ResourceManager.GetString("Unit_BloodGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blood glucose, mmol/l.
        /// </summary>
        internal static string Unit_BloodGlucoseDescription {
            get {
                return ResourceManager.GetString("Unit_BloodGlucoseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на °C.
        /// </summary>
        internal static string Unit_Celsius {
            get {
                return ResourceManager.GetString("Unit_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Degree Celsius, °C.
        /// </summary>
        internal static string Unit_CelsiusDescription {
            get {
                return ResourceManager.GetString("Unit_CelsiusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bpm.
        /// </summary>
        internal static string Unit_HeartRate {
            get {
                return ResourceManager.GetString("Unit_HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bpm.
        /// </summary>
        internal static string Unit_HeartRateDescription {
            get {
                return ResourceManager.GetString("Unit_HeartRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mmHg.
        /// </summary>
        internal static string Unit_MillimetreOfMercury {
            get {
                return ResourceManager.GetString("Unit_MillimetreOfMercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Millimetre of mercury, mmHg.
        /// </summary>
        internal static string Unit_MillimetreOfMercuryDescription {
            get {
                return ResourceManager.GetString("Unit_MillimetreOfMercuryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на min.
        /// </summary>
        internal static string Unit_min {
            get {
                return ResourceManager.GetString("Unit_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на years.
        /// </summary>
        internal static string Unit_years {
            get {
                return ResourceManager.GetString("Unit_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Large loss of heart rate signal.
        /// </summary>
        internal static string WarningLossData {
            get {
                return ResourceManager.GetString("WarningLossData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low battery level.
        /// </summary>
        internal static string WarningLowBatteryLevel {
            get {
                return ResourceManager.GetString("WarningLowBatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии пациента:.
        /// </summary>
        internal static string wqeqw123 {
            get {
                return ResourceManager.GetString("wqeqw123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string Settings_MonitorAutoCompleteRecordByCriteria
        {
            get
            {
                return ResourceManager.GetString("Settings_MonitorAutoCompleteRecordByCriteria", resourceCulture);
            }
        } 
        
        internal static string Dialog_CriteriaMet {
            get {
                return ResourceManager.GetString("Dialog_CriteriaMet", resourceCulture);
            }
        }  
        
        internal static string NetworkUnvailable_MainText {
            get {
                return ResourceManager.GetString("NetworkUnvailable_MainText", resourceCulture);
            }
        }
        
        internal static string NetworkUnvailable_AdditionalText {
            get {
                return ResourceManager.GetString("NetworkUnvailable_AdditionalText", resourceCulture);
            }
        } 
        
        internal static string Loading{
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        } 
        
        internal static string Main_DeviceNotLicense {
            get {
                return ResourceManager.GetString("Main_DeviceNotLicense", resourceCulture);
            }
        }
        
        internal static string Dialog_PregnancyStartNotCorrect {
            get {
                return ResourceManager.GetString("Dialog_PregnancyStartNotCorrect", resourceCulture);
            }
        } 
        
        internal static string Settings_PregnancyWeek {
            get {
                return ResourceManager.GetString("Settings_PregnancyWeek", resourceCulture);
            }
        }
        
        internal static string Settings_PregnancyDay {
            get {
                return ResourceManager.GetString("Settings_PregnancyDay", resourceCulture);
            }
        } 
        
        internal static string About_Instruction
        {
            get {
                return ResourceManager.GetString("About_Instruction", resourceCulture);
            }
        }
    }
}
