//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioss.Ultrasound.Resources.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bioss.Ultrasound.Resources.Localization.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Startup_PermissionsMessage {
            get {
                return ResourceManager.GetString("Startup_PermissionsMessage", resourceCulture);
            }
        }
        
        internal static string Startup_RequestPermissions {
            get {
                return ResourceManager.GetString("Startup_RequestPermissions", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string PermissionDialogQuestion2 {
            get {
                return ResourceManager.GetString("PermissionDialogQuestion2", resourceCulture);
            }
        }
        
        internal static string PermissionDialogTitle {
            get {
                return ResourceManager.GetString("PermissionDialogTitle", resourceCulture);
            }
        }
        
        internal static string BluetoothSearch {
            get {
                return ResourceManager.GetString("BluetoothSearch", resourceCulture);
            }
        }
        
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        internal static string Main_HoldStopButton {
            get {
                return ResourceManager.GetString("Main_HoldStopButton", resourceCulture);
            }
        }
        
        internal static string Dialog_DisconnectMessage {
            get {
                return ResourceManager.GetString("Dialog_DisconnectMessage", resourceCulture);
            }
        }
        
        internal static string Dialog_RecordCompleted {
            get {
                return ResourceManager.GetString("Dialog_RecordCompleted", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        internal static string Menu_AboutDescription {
            get {
                return ResourceManager.GetString("Menu_AboutDescription", resourceCulture);
            }
        }
        
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        internal static string Menu_SettingsDescription {
            get {
                return ResourceManager.GetString("Menu_SettingsDescription", resourceCulture);
            }
        }
        
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string Records_Title {
            get {
                return ResourceManager.GetString("Records_Title", resourceCulture);
            }
        }
        
        internal static string Records_EmptyList {
            get {
                return ResourceManager.GetString("Records_EmptyList", resourceCulture);
            }
        }
        
        internal static string Settings_AutoToco {
            get {
                return ResourceManager.GetString("Settings_AutoToco", resourceCulture);
            }
        }
        
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string Settings_SectionInfo {
            get {
                return ResourceManager.GetString("Settings_SectionInfo", resourceCulture);
            }
        }
        
        internal static string Settings_Organization {
            get {
                return ResourceManager.GetString("Settings_Organization", resourceCulture);
            }
        }
        
        internal static string Settings_OrganizationPlaceholder {
            get {
                return ResourceManager.GetString("Settings_OrganizationPlaceholder", resourceCulture);
            }
        }
        
        internal static string Settings_Doctor {
            get {
                return ResourceManager.GetString("Settings_Doctor", resourceCulture);
            }
        }
        
        internal static string Settings_DoctorPlaceholder {
            get {
                return ResourceManager.GetString("Settings_DoctorPlaceholder", resourceCulture);
            }
        }
        
        internal static string Settings_IsPersonal {
            get {
                return ResourceManager.GetString("Settings_IsPersonal", resourceCulture);
            }
        }
        
        internal static string Settings_IsPersonalDescription {
            get {
                return ResourceManager.GetString("Settings_IsPersonalDescription", resourceCulture);
            }
        }
        
        internal static string Settings_UserName {
            get {
                return ResourceManager.GetString("Settings_UserName", resourceCulture);
            }
        }
        
        internal static string Settings_UserNamePlaceholder {
            get {
                return ResourceManager.GetString("Settings_UserNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string Settings_UserBirthday {
            get {
                return ResourceManager.GetString("Settings_UserBirthday", resourceCulture);
            }
        }
        
        internal static string Settings_UserBirthdayDescriptionNotSelected {
            get {
                return ResourceManager.GetString("Settings_UserBirthdayDescriptionNotSelected", resourceCulture);
            }
        }
        
        internal static string Settings_UserBirthdayDescriptionAge {
            get {
                return ResourceManager.GetString("Settings_UserBirthdayDescriptionAge", resourceCulture);
            }
        }
        
        internal static string Settings_PregnancyStart {
            get {
                return ResourceManager.GetString("Settings_PregnancyStart", resourceCulture);
            }
        }
        
        internal static string Settings_PregnancyStartDescriptionNotSelected {
            get {
                return ResourceManager.GetString("Settings_PregnancyStartDescriptionNotSelected", resourceCulture);
            }
        }
        
        internal static string Settings_PregnancyStartDescriptionTime {
            get {
                return ResourceManager.GetString("Settings_PregnancyStartDescriptionTime", resourceCulture);
            }
        }
        
        internal static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings_Connection", resourceCulture);
            }
        }
        
        internal static string Settings_AutoConnect {
            get {
                return ResourceManager.GetString("Settings_AutoConnect", resourceCulture);
            }
        }
        
        internal static string Settings_AutoConnectDescription {
            get {
                return ResourceManager.GetString("Settings_AutoConnectDescription", resourceCulture);
            }
        }
        
        internal static string Settings_Monitor {
            get {
                return ResourceManager.GetString("Settings_Monitor", resourceCulture);
            }
        }
        
        internal static string Settings_AutoMonitor {
            get {
                return ResourceManager.GetString("Settings_AutoMonitor", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorConfirmRecordCompletion {
            get {
                return ResourceManager.GetString("Settings_MonitorConfirmRecordCompletion", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorConfirmRecordCompletionDescription {
            get {
                return ResourceManager.GetString("Settings_MonitorConfirmRecordCompletionDescription", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorFinishTimes {
            get {
                return ResourceManager.GetString("Settings_MonitorFinishTimes", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorFinishMinuteFormat {
            get {
                return ResourceManager.GetString("Settings_MonitorFinishMinuteFormat", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorSoundBatteryLow {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundBatteryLow", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorSoundLossData {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundLossData", resourceCulture);
            }
        }
        
        internal static string Settings_MonitorSoundLevel {
            get {
                return ResourceManager.GetString("Settings_MonitorSoundLevel", resourceCulture);
            }
        }
        
        internal static string Settings_SectionPdf {
            get {
                return ResourceManager.GetString("Settings_SectionPdf", resourceCulture);
            }
        }
        
        internal static string Settings_PdfRecordingSpeed {
            get {
                return ResourceManager.GetString("Settings_PdfRecordingSpeed", resourceCulture);
            }
        }
        
        internal static string Settings_PdfRecordingSpeedFormat {
            get {
                return ResourceManager.GetString("Settings_PdfRecordingSpeedFormat", resourceCulture);
            }
        }
        
        internal static string Settings_SectionChart {
            get {
                return ResourceManager.GetString("Settings_SectionChart", resourceCulture);
            }
        }
        
        internal static string Settings_ChartScale {
            get {
                return ResourceManager.GetString("Settings_ChartScale", resourceCulture);
            }
        }
        
        internal static string Settings_ChartScalePageTitle {
            get {
                return ResourceManager.GetString("Settings_ChartScalePageTitle", resourceCulture);
            }
        }
        
        internal static string Settings_ChartVariantsMinuteFormat {
            get {
                return ResourceManager.GetString("Settings_ChartVariantsMinuteFormat", resourceCulture);
            }
        }
        
        internal static string Settings_ChartFHRArea {
            get {
                return ResourceManager.GetString("Settings_ChartFHRArea", resourceCulture);
            }
        }
        
        internal static string Settings_ChartYScaleFormat {
            get {
                return ResourceManager.GetString("Settings_ChartYScaleFormat", resourceCulture);
            }
        }
        
        internal static string Settings_PregnancyNumber {
            get {
                return ResourceManager.GetString("Settings_PregnancyNumber", resourceCulture);
            }
        }
        
        internal static string Record_DialogDeleteTitle {
            get {
                return ResourceManager.GetString("Record_DialogDeleteTitle", resourceCulture);
            }
        }
        
        internal static string Record_DialogDeleteMessage {
            get {
                return ResourceManager.GetString("Record_DialogDeleteMessage", resourceCulture);
            }
        }
        
        internal static string LossPercentage {
            get {
                return ResourceManager.GetString("LossPercentage", resourceCulture);
            }
        }
        
        internal static string LossPercentageMin {
            get {
                return ResourceManager.GetString("LossPercentageMin", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string PDF_UserBirthdayDescriptionAge {
            get {
                return ResourceManager.GetString("PDF_UserBirthdayDescriptionAge", resourceCulture);
            }
        }
        
        internal static string PDF_NotSpecified {
            get {
                return ResourceManager.GetString("PDF_NotSpecified", resourceCulture);
            }
        }
        
        internal static string PDF_HeaderLeftCorner {
            get {
                return ResourceManager.GetString("PDF_HeaderLeftCorner", resourceCulture);
            }
        }
        
        internal static string PDF_HeaderDateOfResearch {
            get {
                return ResourceManager.GetString("PDF_HeaderDateOfResearch", resourceCulture);
            }
        }
        
        internal static string PDF_HeaderPatient {
            get {
                return ResourceManager.GetString("PDF_HeaderPatient", resourceCulture);
            }
        }
        
        internal static string PDF_HeaderDoctor {
            get {
                return ResourceManager.GetString("PDF_HeaderDoctor", resourceCulture);
            }
        }
        
        internal static string PDF_FooterPageNumbers {
            get {
                return ResourceManager.GetString("PDF_FooterPageNumbers", resourceCulture);
            }
        }
        
        internal static string PDF_FooterSN {
            get {
                return ResourceManager.GetString("PDF_FooterSN", resourceCulture);
            }
        }
        
        internal static string PDF_TableCTGParameters {
            get {
                return ResourceManager.GetString("PDF_TableCTGParameters", resourceCulture);
            }
        }
        
        internal static string PDF_TableMotherParameters {
            get {
                return ResourceManager.GetString("PDF_TableMotherParameters", resourceCulture);
            }
        }
        
        internal static string PDF_RecordingDuration {
            get {
                return ResourceManager.GetString("PDF_RecordingDuration", resourceCulture);
            }
        }
        
        internal static string PDF_FetalMovements {
            get {
                return ResourceManager.GetString("PDF_FetalMovements", resourceCulture);
            }
        }
        
        internal static string PDF_GestationalAge {
            get {
                return ResourceManager.GetString("PDF_GestationalAge", resourceCulture);
            }
        }
        
        internal static string PDF_SignaLoss {
            get {
                return ResourceManager.GetString("PDF_SignaLoss", resourceCulture);
            }
        }
        
        internal static string PDF_Temperature {
            get {
                return ResourceManager.GetString("PDF_Temperature", resourceCulture);
            }
        }
        
        internal static string PDF_Pulse {
            get {
                return ResourceManager.GetString("PDF_Pulse", resourceCulture);
            }
        }
        
        internal static string PDF_Sugar {
            get {
                return ResourceManager.GetString("PDF_Sugar", resourceCulture);
            }
        }
        
        internal static string PDF_HeartRate {
            get {
                return ResourceManager.GetString("PDF_HeartRate", resourceCulture);
            }
        }
        
        internal static string PDF_Comment {
            get {
                return ResourceManager.GetString("PDF_Comment", resourceCulture);
            }
        }
        
        internal static string PDF_DoctorsConclusion {
            get {
                return ResourceManager.GetString("PDF_DoctorsConclusion", resourceCulture);
            }
        }
        
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        internal static string TurnOnYourDevice {
            get {
                return ResourceManager.GetString("TurnOnYourDevice", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Title {
            get {
                return ResourceManager.GetString("BiometricPopup_Title", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Temperature {
            get {
                return ResourceManager.GetString("BiometricPopup_Temperature", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Sugar {
            get {
                return ResourceManager.GetString("BiometricPopup_Sugar", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Diastolic {
            get {
                return ResourceManager.GetString("BiometricPopup_Diastolic", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Systolic {
            get {
                return ResourceManager.GetString("BiometricPopup_Systolic", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Pulse {
            get {
                return ResourceManager.GetString("BiometricPopup_Pulse", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_Comment {
            get {
                return ResourceManager.GetString("BiometricPopup_Comment", resourceCulture);
            }
        }
        
        internal static string BiometricPopup_ErrorEnter {
            get {
                return ResourceManager.GetString("BiometricPopup_ErrorEnter", resourceCulture);
            }
        }
        
        internal static string Unit_Celsius {
            get {
                return ResourceManager.GetString("Unit_Celsius", resourceCulture);
            }
        }
        
        internal static string Unit_BloodGlucose {
            get {
                return ResourceManager.GetString("Unit_BloodGlucose", resourceCulture);
            }
        }
        
        internal static string Unit_MillimetreOfMercury {
            get {
                return ResourceManager.GetString("Unit_MillimetreOfMercury", resourceCulture);
            }
        }
        
        internal static string Unit_HeartRate {
            get {
                return ResourceManager.GetString("Unit_HeartRate", resourceCulture);
            }
        }
        
        internal static string Unit_min {
            get {
                return ResourceManager.GetString("Unit_min", resourceCulture);
            }
        }
        
        internal static string Unit_years {
            get {
                return ResourceManager.GetString("Unit_years", resourceCulture);
            }
        }
        
        internal static string Unit_CelsiusDescription {
            get {
                return ResourceManager.GetString("Unit_CelsiusDescription", resourceCulture);
            }
        }
        
        internal static string Unit_BloodGlucoseDescription {
            get {
                return ResourceManager.GetString("Unit_BloodGlucoseDescription", resourceCulture);
            }
        }
        
        internal static string Unit_MillimetreOfMercuryDescription {
            get {
                return ResourceManager.GetString("Unit_MillimetreOfMercuryDescription", resourceCulture);
            }
        }
        
        internal static string Unit_HeartRateDescription {
            get {
                return ResourceManager.GetString("Unit_HeartRateDescription", resourceCulture);
            }
        }
        
        internal static string WarningLowBatteryLevel {
            get {
                return ResourceManager.GetString("WarningLowBatteryLevel", resourceCulture);
            }
        }
        
        internal static string WarningLossData {
            get {
                return ResourceManager.GetString("WarningLossData", resourceCulture);
            }
        }
        
        internal static string Chart_FHRAxysTitle {
            get {
                return ResourceManager.GetString("Chart_FHRAxysTitle", resourceCulture);
            }
        }
        
        internal static string Chart_TOCOAxysTitle {
            get {
                return ResourceManager.GetString("Chart_TOCOAxysTitle", resourceCulture);
            }
        }
        
        internal static string DocPrivacy {
            get {
                return ResourceManager.GetString("DocPrivacy", resourceCulture);
            }
        }
    }
}
